RideContentType:
    type: object
    inherits:
        - BaseDomainContentType
    config:
        interfaces:
            - DomainContentType
        fields:
            name:
                type: TextLineFieldDefinition
                resolve: '@=value.getFieldDefinition("name")'
            photo:
                type: MatrixFieldDefinition
                resolve: '@=value.getFieldDefinition("photo")'
            description:
                type: MatrixFieldDefinition
                resolve: '@=value.getFieldDefinition("description")'
            startingPoint:
                type: MatrixFieldDefinition
                resolve: '@=value.getFieldDefinition("starting_point")'
            endingPoint:
                type: MatrixFieldDefinition
                resolve: '@=value.getFieldDefinition("ending_point")'
            length:
                type: IntegerFieldDefinition
                resolve: '@=value.getFieldDefinition("length")'
            landmarks:
                type: RelationListFieldDefinition
                resolve: '@=value.getFieldDefinition("landmarks")'
