# /config/packages/app/views.yaml
ezdesign:
  # You declare every available designs under 'design_list'
  design_list:
    app_design: [ 'juan_ride']
ezplatform:
  system:
    default:
      field_templates:
        - { template: 'point2d_field.html.twig', priority: 0 }
      fielddefinition_edit_templates:
        - { template: 'point2d_field_type_definition.html.twig', priority: 0 }
    front_group:
      design: 'app_design'
      # pagelayout: '@ezdesign/pagelayout.html.twig'
      content_view:
        full:
          bike_ride:
            template: "@ezdesign/full/bike_ride.html.twig"
            match:
              Identifier\ContentType: [ 'ride' ]
          home_page:
            controller: ez_query::ContentQueryAction
            template: '@ezdesign/full/all_rides.html.twig'
            match:
              Id\Location: 54
            params:
              query:
                query_type: BikeRideList
                limit: 4
                assign_results_to: bike_ride_list
          pages:
            template: "@ezdesign/full/page.html.twig"
            match:
              Identifier\ContentType: [ 'page' ]
          landmark:
            template: "@ezdesign/full/landmark.html.twig"
            match:
              Identifier\ContentType: [ 'landmark' ]
        line:
          landmark:
            template: "@ezdesign/line/landmark.html.twig"
            match:
              Identifier\ContentType: [ 'landmark' ]
