ezdesign:
  # You declare every available designs under 'design_list'
  design_list:
    app_design: [ 'standard']
ezplatform:
  system:
    site:
      design: 'app_design'
      # existing content_view keys
      user_registration:
        templates:
          form: '@ezdesign/user/registration_form.html.twig'
          confirmation: '@ezdesign/user/registration_confirmation.html.twig'
      content_view:
        line:
          ride:
            template: '@ezdesign/line/rides.html.twig'
            match:
              Identifier\ContentType: ride
          landmark:
            template: '@ezdesign/line/landmark.html.twig'
            match:
              Identifier\ContentType: landmark
        full:
          home_page:
            controller: ez_query::pagingQueryAction
            template: '@ezdesign/full/home_page.html.twig'
            match:
              Id\Location: 2
            params:
              query:
                query_type: Ride
                limit: 4
                assign_results_to: rides
          ride:
            controller: App\Controller\RideController::viewRideWithLandmarksAction
            template: '@ezdesign/full/ride.html.twig'
            match:
              Identifier\ContentType: ride