ezplatform:
  system:
    site:
      # existing content_view keys
      user_registration:
        templates:
          form: themes/standard/user/registration_form.html.twig
          confirmation: themes/standard/user/registration_confirmation.html.twig
      content_view:
        line:
          ride:
            template: themes/standard/line/rides.html.twig
            match:
              Identifier\ContentType: ride
          landmark:
            template: themes/standard/line/landmark.html.twig
            match:
              Identifier\ContentType: landmark
        full:
          home_page:
            controller: ez_query::pagingQueryAction
            template: themes/standard/full/home_page.html.twig
            match:
              Id\Location: 2
            params:
              query:
                query_type: Ride
                limit: 4
                assign_results_to: rides
          ride:
            controller: App\Controller\RideController::viewRideWithLandmarksAction
            template: themes/standard/full/ride.html.twig
            match:
              Identifier\ContentType: ride